#!/usr/bin/env bash
# installs nginx
# configure nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World! SUCCESS' > /var/www/html/index.nginx-debian.html
service nginx start
