#!/usr/bin/env bash
#configure web-02 to be identical to web-01
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#  The name of the custom HTTP header must be X-Served-By
#  The value of the custom HTTP header must be the hostname of the server Nginx is running on

#install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Displaying "Hello Success! page
echo "Hello SUCCESS!" | sudo tee /var/www/html/index.html

# Redirection
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.linkedin.com/in/nancy-ngatia;\n	}' /etc/nginx/sites-available/default


# Create a custom 404 error_page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 error_page 
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default


# Add custom header configuration to Nginx
sudo sed -i "/^http {/a \    add_header X-Served-By $hostname;" /etc/nginx/sites-available/default

# restart the web server after updating the settings
sudo service nginx restart
