#!/usr/bin/env bash
#Script that install and configures HAproxy on my lb-01 server.
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script

#Install haproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

#configure haproxy to share request between two servers
echo  "
frontend shiicodes-frontend
   bind *:80
   timeout client 60s
   mode http
   default_backend shiicodes-backend

backend shiicodes-backend
   balance roundrobin
   timeout connect 10s
   timeout server 100s
   mode http
   server 98929-web-01 34.203.77.202:80 check
   server 98929-web-02 54.158.218.91:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null

#Enable haproxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#Restart haproxy
sudo service haproxy restart
